### ISSUE TITLE
Jumpers dual can bus shield

### ISSUE THREAD

**Issue by JRMA67** [pavelmalik/BMWCanBridge#3]
Sir
Excellent diy! Just one question.
Do the jumpers (both) from the can bus shield have to be removed?

Thanks in advance

Javier

**Comment by pavelmalik** [comment]
Hey Javier, you have to remove both the jumpers - all they do is add
resistance across the two data lines, which is used for PT-can, rather than
K-can. The fault tolerant k-can lines just need resistance to ground.

**Comment by JRMA67** [comment]
Thank you very much! Done. Everything works. Just one detail, the arduino due board should be modified so resets automatically via 10k resistor.
https://copperhilltech.com/blog/arduino-due-design-flaw-due-wont-start-after-poweroffon-requires-reset/

Regards

**Comment by pavelmalik** [comment]
Ah, yupp - I've wasted a lot of time on that one in particular before I found it on the one of the arduino forums. Soldering in regular axial ones works as well.

**Comment by petrunov** [comment]
Hello - both of you have not provded email so I am using this as a means to contact with you - I have practically zero experience with Arduino or wiring but I have experience with programming and I can understand how I need to edit this code to update it with the VIN of the donor car. 

Do you think a newbie could manage to get the night vision workign by buying a board and trying this code? 

 I have someone to help me with the wiring if necessary - I am unsure about how is this code uploaded to the Arduino and if there would be many caveats... the other option is to just buy a pre-made emulator for 150EUR but I am also interested into doing it myself.

**Comment by JRMA67** [comment]
> Hello - both of you have not provded email so I am using this as a means to contact with you - I have practically zero experience with Arduino or wiring but I have experience with programming and I can understand how I need to edit this code to update it with the VIN of the donor car.
> 
> Do you think a newbie could manage to get the night vision workign by buying a board and trying this code?
> 
> I have someone to help me with the wiring if necessary - I am unsure about how is this code uploaded to the Arduino and if there would be many caveats... the other option is to just buy a pre-made emulator for 150EUR but I am also interested into doing it myself.

I did it! No problem at all. Quiet easy, I made my own harness as well. I am not an expert in arduino, actually was my first arduino due first project! Follow the instructions from pavelmalik!
Note! You need to modify the due board so it will reset automatically!
